---
- id: myChecks
  name: myChecks
  description: This hook runs checkov.
  entry: hooks/run.sh
  language: script
  pass_filenames: true
  always_run: false
  files: \.tf$
  exclude: \.+.terraform\/.*$
  require_serial: true