---
- id: myChecks
  name: myChecks
  description: runs myChecks over a project, cross platform compatible
  entry: myChecks
  language: python
  language_version: python3.7
  always_run: true
  pass_filenames: false
  verbose: true